#!/usr/bin/env node
/**
 * Round E: the rebuild-in-place and remove flows.
 * Build a wall, customize it like a user would (slider value + an own layer in the comp),
 * rebuild with different settings under the same comp name, and assert nothing of the
 * user's work is lost, nothing is duplicated, and remove() cleans up completely.
 */
import { execFileSync, execSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const assets = join(root, '.test-assets')
const dir = join(root, '.test-out', 'E')
const AE = 'Adobe After Effects 2025'
if (!existsSync(join(assets, 'colors.json'))) execFileSync('node', [join(root, 'scripts/make-test-videos.mjs')], { stdio: 'inherit' })
rmSync(dir, { recursive: true, force: true })
mkdirSync(dir, { recursive: true })

const clips = (n) => Array.from({ length: n }, (_, i) => join(assets, `clip-${String(i + 1).padStart(2, '0')}.mp4`))
const base = {
  videos: clips(12),
  compName: 'Wallmaker test E',
  compW: 1280, compH: 720, fps: 30, durationSec: 8,
  gridMode: 'manual', rows: 3, cols: 4, gap: 8, margin: 20, heroes: 0,
  fill: 'cover', cornerRadius: 0, assign: 'sequential',
  randomStart: true, loop: true, muteAudio: true, labels: false,
  background: 'dark', bgColor: '#101014',
  animate: true, reveal: 'random', revealStart: 0.3, revealDuration: 3,
  screenAnim: 'fade', screenAnimFrames: 6, jitter: 0.2, deadPct: 0, dropouts: 0, seed: 3,
  focus: true, focusRadius: 400, focusZoom: 140, focusDim: 20,
}
const second = { ...base, rows: 5, cols: 5, labels: true, borders: true, borderWidth: 2, borderColor: '#303030', focus: false, videos: clips(8) }

for (const [name, cfg] of [['wall1', base], ['wall2', second]]) {
  const cfgPath = join(dir, `${name}-cfg.json`)
  writeFileSync(cfgPath, JSON.stringify(cfg))
  execFileSync('npx', ['tsx', join(root, 'test/make-scene.ts'), cfgPath, join(dir, `${name}.json`)], { stdio: 'pipe', cwd: root })
}
const wall2 = JSON.parse(readFileSync(join(dir, 'wall2.json'), 'utf8'))

const j = (v) => JSON.stringify(JSON.stringify(v))
const runner = `// generated by test/run-rebuild.mjs -- ES3
try { app.preferences.savePrefAsLong('Main Pref Section', 'Pref_SCRIPTING_FILE_NETWORK_SECURITY', 1); } catch (e) {}
$.evalFile(${JSON.stringify(join(root, 'cep/host/index.jsx'))});
function WRITE(name, s) { var f = new File(${JSON.stringify(dir)} + '/' + name); f.encoding = 'UTF-8'; f.open('w'); f.write(s); f.close(); }
function BUILD(jsonPath) {
  WALLMAKER.begin(WALLMAKER_JSON.stringify({ jsonPath: jsonPath, folder: ${JSON.stringify(dir)} }));
  var guard = 0;
  while (guard++ < 200) { var s = WALLMAKER_JSON.parse(WALLMAKER.step('{"count":25}')); if (s.done >= s.total) break; }
  return WALLMAKER_JSON.parse(WALLMAKER.finish());
}
function findComp(name) { var it = app.project.items; for (var i = 1; i <= it.length; i++) if (it[i] instanceof CompItem && it[i].name === name) return it[i]; return null; }
try {
  try { app.project.close(CloseOptions.DO_NOT_SAVE_CHANGES); } catch (e) {}
  app.newProject();
  var fin1 = BUILD(${JSON.stringify(join(dir, 'wall1.json'))});
  var comp = findComp(${j(base.compName)}.replace(/"/g, ''));
  var compId = comp.id;
  // -- the user customizes: gap slider to 33, a layer of their own into the comp
  var ctl = null, focusSeen1 = false;
  for (var i = 1; i <= comp.numLayers; i++) {
    if (comp.layer(i).name === 'Wallmaker Controls') ctl = comp.layer(i);
    if (comp.layer(i).name === 'Wallmaker Focus') focusSeen1 = true;
  }
  ctl.property('ADBE Effect Parade').property('Gap (px)').property(1).setValue(33);
  var userLayer = comp.layers.addSolid([1, 0, 0], 'user layer', 50, 50, 1, comp.duration);
  userLayer.comment = 'mine';
  // -- rebuild with different settings, same comp name
  var fin2 = BUILD(${JSON.stringify(join(dir, 'wall2.json'))});
  var comps = 0, screens = 0, labels = 0, borders = 0, userSeen = false, focusSeen2 = false, gapVal = -1;
  var items = app.project.items;
  for (var k = 1; k <= items.length; k++) if (items[k] instanceof CompItem && items[k].name === ${j(base.compName)}.replace(/"/g, '')) comps++;
  var c2 = findComp(${j(base.compName)}.replace(/"/g, ''));
  var sameId = c2.id === compId;
  for (var m = 1; m <= c2.numLayers; m++) {
    var l = c2.layer(m);
    if (l.comment && l.comment.indexOf('wallmaker-screen') === 0) screens++;
    if (l.comment && l.comment.indexOf('wallmaker-label ') === 0) labels++;
    if (l.comment === 'wallmaker-borders') borders++;
    if (l.name === 'user layer') userSeen = true;
    if (l.name === 'Wallmaker Focus') focusSeen2 = true;
    if (l.name === 'Wallmaker Controls') gapVal = l.property('ADBE Effect Parade').property('Gap (px)').property(1).value;
  }
  // -- remove the build entirely
  var rem = WALLMAKER_JSON.parse(WALLMAKER.remove(WALLMAKER_JSON.stringify({ buildKey: ${j(wall2.buildKey)}.replace(/"/g, '') })));
  var compsAfter = 0;
  var items2 = app.project.items;
  for (var q = 1; q <= items2.length; q++) if (items2[q] instanceof CompItem && items2[q].name === ${j(base.compName)}.replace(/"/g, '')) compsAfter++;
  WRITE('result.json', WALLMAKER_JSON.stringify({
    ok: true, fin1: fin1, fin2: fin2,
    sameCompId: sameId, comps: comps, screens: screens, labels: labels, borders: borders,
    userSeen: userSeen, focusSeen1: focusSeen1, focusSeen2: focusSeen2, gapVal: gapVal,
    removed: rem.removed, compsAfter: compsAfter
  }));
} catch (e) {
  WRITE('result.json', WALLMAKER_JSON.stringify({ ok: false, error: String(e && e.message ? e.message + ' (line ' + e.line + ')' : e) }));
}
`
writeFileSync(join(dir, 'runner.jsx'), runner)
console.log('=== Round E: build → customize → rebuild → remove…')
execSync(`osascript -e 'with timeout of 900 seconds' -e 'tell application "${AE}" to DoScript "$.evalFile(\\"${join(dir, 'runner.jsx')}\\")"' -e 'end timeout'`, { stdio: 'inherit' })
const r = JSON.parse(readFileSync(join(dir, 'result.json'), 'utf8'))
if (!r.ok) throw new Error(`Round E failed in AE: ${r.error}`)

const checks = [
  ['first build: 12 screens', r.fin1.screens === 12],
  ['second build: 25 screens', r.fin2.screens === 25 && r.screens === 25],
  ['comp item identity preserved', r.sameCompId === true],
  ['exactly one comp with that name', r.comps === 1 && r.fin2.compName === base.compName],
  ['labels appeared on rebuild', r.labels === 25],
  ['borders layer appeared on rebuild', r.borders === 1],
  ["user's own layer survived", r.userSeen === true],
  ["user's slider value survived (33)", Math.abs(r.gapVal - 33) < 0.01],
  ['focus null existed after build 1', r.focusSeen1 === true],
  ['stale focus null removed when the feature is off', r.focusSeen2 === false],
  ['remove() removed the build', r.removed === true && r.compsAfter === 0],
]
let bad = 0
for (const [name, ok] of checks) {
  console.log(` ${ok ? '✓' : '✗'} ${name}`)
  if (!ok) bad++
}
if (bad) {
  console.log(JSON.stringify(r, null, 2))
  process.exit(1)
}
console.log('✓ Round E passed')
