#!/usr/bin/env node
/**
 * Round H: the things that go wrong in a real project.
 * A source goes offline, the user deletes the Camera null, renames the Controls null, deletes the
 * Layout guide, another comp already owns the name, or a switch is flipped before anything exists.
 * None of these may take the build down or silently lose the rig.
 *
 * ⚠ Closes the current AE project WITHOUT saving.
 */
import { execFileSync, execSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const assets = join(root, '.test-assets')
const dir = join(root, '.test-out', 'H')
const AE = 'Adobe After Effects 2025'
if (!existsSync(join(assets, 'colors.json'))) execFileSync('node', [join(root, 'scripts/make-test-videos.mjs')], { stdio: 'inherit' })
rmSync(dir, { recursive: true, force: true })
mkdirSync(join(dir, 'clips'), { recursive: true })

// our own copies, so one of them can be taken away mid-test
const OFFLINE = 'goes-offline.mp4'
const clips = Array.from({ length: 6 }, (_, i) => {
  const name = i === 3 ? OFFLINE : `keep-${i}.mp4`
  const to = join(dir, 'clips', name)
  copyFileSync(join(assets, `clip-0${i + 1}.mp4`), to)
  return to
})

const cfg = {
  videos: clips,
  compName: 'Wallmaker test H',
  compW: 960, compH: 540, fps: 30, durationSec: 6,
  gridMode: 'manual', rows: 3, cols: 3, gap: 6, margin: 0, cellAspect: 'fill',
  fill: 'cover', assign: 'shuffle', randomStart: true, loop: true, muteAudio: true,
  background: 'solid', bgColor: '#101014', featured: 1,
  intro: 'zoomOut', introHold: 0.5, introDur: 1, outro: 'none',
  animate: true, reveal: 'random', revealStart: 0.2, revealDuration: 2,
  screenAnim: 'fade', screenAnimFrames: 6, jitter: 0.2, deadPct: 0, seed: 2,
}
writeFileSync(join(dir, 'cfg.json'), JSON.stringify(cfg))
execFileSync('npx', ['tsx', join(root, 'test/make-scene.ts'), join(dir, 'cfg.json'), join(dir, 'wall.json')], { stdio: 'pipe', cwd: root })
const wall = JSON.parse(readFileSync(join(dir, 'wall.json'), 'utf8'))
const j = (v) => JSON.stringify(JSON.stringify(v))

const runner = `// generated by test/run-robust.mjs -- ES3
try { app.preferences.savePrefAsLong('Main Pref Section', 'Pref_SCRIPTING_FILE_NETWORK_SECURITY', 1); } catch (e) {}
$.evalFile(${JSON.stringify(join(root, 'cep/host/index.jsx'))});
function W(n, s) { var f = new File(${JSON.stringify(dir)} + '/' + n); f.encoding = 'UTF-8'; f.open('w'); f.write(s); f.close(); }
function findComp(nm) { var it = app.project.items; for (var i = 1; i <= it.length; i++) if (it[i] instanceof CompItem && it[i].name === nm) return it[i]; return null; }
function byName(c, nm) { for (var i = 1; i <= c.numLayers; i++) if (c.layer(i).name === nm) return c.layer(i); return null; }
function tagged(c, t) { var n = 0; for (var i = 1; i <= c.numLayers; i++) if (String(c.layer(i).comment || '').indexOf(t) === 0) n++; return n; }
function BUILD() {
  WALLMAKER.begin(WALLMAKER_JSON.stringify({ jsonPath: ${JSON.stringify(join(dir, 'wall.json'))}, folder: ${JSON.stringify(dir)} }));
  var g = 0; while (g++ < 200) { var s = WALLMAKER_JSON.parse(WALLMAKER.step('{"count":25}')); if (s.done >= s.total) break; }
  return WALLMAKER_JSON.parse(WALLMAKER.finish());
}
var r = {};
try {
  try { app.project.close(CloseOptions.DO_NOT_SAVE_CHANGES); } catch (e) {}
  app.newProject();
  var key = ${j(wall.buildKey)}.replace(/"/g, '');
  r.proxNone = WALLMAKER_JSON.parse(WALLMAKER.proxies(WALLMAKER_JSON.stringify({ buildKey: key })));
  r.layNone = WALLMAKER_JSON.parse(WALLMAKER.layout(WALLMAKER_JSON.stringify({ buildKey: key, on: true })));
  r.fin1 = BUILD();
  var c = findComp('Wallmaker test H');
  byName(c, 'Wallmaker Camera').remove();
  r.fin2 = BUILD(); c = findComp('Wallmaker test H');
  r.camRebuilt = tagged(c, 'wallmaker-camera');
  r.ctlParent = byName(c, 'Wallmaker Controls').parent ? byName(c, 'Wallmaker Controls').parent.name : null;
  byName(c, 'Wallmaker Controls').name = 'My wall null';
  r.fin3 = BUILD(); c = findComp('Wallmaker test H');
  r.ctlKept = tagged(c, 'wallmaker-controls');
  r.ctlName = (function () { for (var i = 1; i <= c.numLayers; i++) { var l = c.layer(i); if (String(l.comment || '').indexOf('wallmaker-controls') === 0) return l.name; } return null; })();
  var mat = byName(c, 'Wallmaker Layout'); if (mat) mat.remove();
  r.layMissing = WALLMAKER_JSON.parse(WALLMAKER.layout(WALLMAKER_JSON.stringify({ buildKey: key, on: true })));
  r.fin4 = BUILD();
  r.layBack = WALLMAKER_JSON.parse(WALLMAKER.layout(WALLMAKER_JSON.stringify({ buildKey: key, on: true })));
  WALLMAKER.layout(WALLMAKER_JSON.stringify({ buildKey: key, on: false }));
  WALLMAKER.remove(WALLMAKER_JSON.stringify({ buildKey: key }));
  var foreign = app.project.items.addComp('Wallmaker test H', 100, 100, 1, 1, 30);
  try { BUILD(); r.clash = ''; } catch (eC) { r.clash = String(eC.message); }
  foreign.remove();
  r.fin5 = BUILD();
  var gone = new File(${JSON.stringify(join(dir, 'clips', OFFLINE))}); gone.remove();
  var proj = app.project;
  for (var i = 1; i <= proj.numItems; i++) { var it = proj.item(i); if (it instanceof FootageItem && it.name === ${j(OFFLINE)}.replace(/"/g, '')) { try { it.replace(new File(${JSON.stringify(join(dir, 'clips', 'nope.mp4'))})); } catch (e2) {} } }
  r.fin6 = BUILD();
  r.screensAfterOffline = tagged(findComp('Wallmaker test H'), 'wallmaker-screen');
  var stray = 0; var its = app.project.items;
  for (var q = 1; q <= its.length; q++) if (its[q] instanceof CompItem && its[q].comment === 'wallmaker-scratch') stray++;
  r.strayScratch = stray;
  r.ok = true;
} catch (e) { r.ok = false; r.error = String(e && e.message ? e.message + ' (line ' + e.line + ')' : e); }
W('result.json', WALLMAKER_JSON.stringify(r));
`
writeFileSync(join(dir, 'runner.jsx'), runner)
console.log('=== Round H: offline sources, a damaged rig, a name clash…')
execSync(`osascript -e 'with timeout of 900 seconds' -e 'tell application "${AE}" to DoScript "$.evalFile(\\"${join(dir, 'runner.jsx')}\\")"' -e 'end timeout'`, { stdio: 'inherit' })
const r = JSON.parse(readFileSync(join(dir, 'result.json'), 'utf8'))
if (!r.ok) throw new Error(`Round H failed in AE: ${r.error}`)

const n = wall.screens.length
const checks = [
  ['switches report "no build" instead of throwing', r.proxNone.found === false && r.layNone.found === false],
  [`first build: ${n} screens`, r.fin1.screens === n],
  ['a deleted Camera null is rebuilt and re-parented', r.camRebuilt === 1 && r.ctlParent === 'Wallmaker Camera'],
  ['a renamed Controls null is found by tag, not name, and keeps its name', r.ctlKept === 1 && r.ctlName === 'My wall null'],
  ['toggling a deleted Layout guide reports "not found"', r.layMissing.found === false],
  ['…and a rebuild brings the guide back', r.layBack.found === true && r.layBack.on === true],
  ['a foreign comp with the same name is refused, clearly', /already exists/.test(r.clash)],
  ['an OFFLINE source is skipped and the rest of the wall still builds', r.fin6.screens === n - 1 && r.fin6.skipped.length === 1, JSON.stringify(r.fin6.skipped)],
  ['every screen that could be built, was', r.screensAfterOffline === n - 1],
  ['no working comps left behind', r.strayScratch === 0],
]
let bad = 0
for (const [name, ok, detail] of checks) {
  console.log(` ${ok ? '✓' : '✗'} ${name}${!ok && detail ? ` — ${detail}` : ''}`)
  if (!ok) bad++
}
if (bad) {
  console.log(JSON.stringify(r, null, 2))
  process.exit(1)
}
console.log('✓ Round H passed')
