#!/usr/bin/env node
/**
 * Round E: the rebuild-in-place / remove flows and THE REBUILD CONTRACT, both directions.
 * Build a wall, rebuild it with different settings under the same comp name, and assert:
 *   - untouched sliders and untouched camera keyframes FOLLOW the panel,
 *   - a slider the user changed and camera keyframes the user retimed are KEPT verbatim,
 *   - the user's own layers survive, nothing duplicates, and remove() cleans up completely.
 */
import { execFileSync, execSync } from 'node:child_process'
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const assets = join(root, '.test-assets')
const dir = join(root, '.test-out', 'E')
const AE = 'Adobe After Effects 2025'
if (!existsSync(join(assets, 'colors.json'))) execFileSync('node', [join(root, 'scripts/make-test-videos.mjs')], { stdio: 'inherit' })
rmSync(dir, { recursive: true, force: true })
mkdirSync(dir, { recursive: true })

const clips = (n) => Array.from({ length: n }, (_, i) => join(assets, `clip-${String(i + 1).padStart(2, '0')}.mp4`))
const base = {
  videos: clips(12),
  compName: 'Wallmaker test E',
  compW: 1280, compH: 720, fps: 30, durationSec: 8,
  gridMode: 'manual', rows: 3, cols: 4, gap: 8, margin: 20,
  fill: 'cover', cornerRadius: 0, assign: 'sequential',
  randomStart: true, loop: true, muteAudio: true,
  background: 'solid', bgColor: '#101014',
  featured: 2, intro: 'zoomOut', introHold: 1, introDur: 2,
  animate: true, reveal: 'random', revealStart: 0.3, revealDuration: 3,
  screenAnim: 'fade', screenAnimFrames: 6, jitter: 0.2, deadPct: 0, seed: 3,
}
// second build: a different grid, a different camera move, a different reveal start
const second = { ...base, rows: 5, cols: 5, videos: clips(8), revealStart: 1.7, introHold: 0.5, introDur: 1.5 }
// third build: changed again -- but by now the user has retimed the camera by hand
const third = { ...second, revealStart: 2.4, introHold: 1.2, introDur: 3 }

const walls = {}
for (const [name, cfg] of [['wall1', base], ['wall2', second], ['wall3', third]]) {
  const cfgPath = join(dir, `${name}-cfg.json`)
  writeFileSync(cfgPath, JSON.stringify(cfg))
  execFileSync('npx', ['tsx', join(root, 'test/make-scene.ts'), cfgPath, join(dir, `${name}.json`)], { stdio: 'pipe', cwd: root })
  walls[name] = JSON.parse(readFileSync(join(dir, `${name}.json`), 'utf8'))
}
/** the zoom keyframes a plan should produce, as [time, value] pairs */
const planKeys = (wall) => {
  const c = wall.camera
  const k = []
  if (c?.intro) {
    if (c.intro.hold > 0) k.push([0, 100])
    k.push([c.intro.hold, 100], [c.intro.end, 0])
  }
  if (c?.outro) k.push([c.outro.start, 0], [c.outro.end, 100])
  return k
}
const sameKeys = (got, want) => got.length === want.length && got.every((k, i) => Math.abs(k[0] - want[i][0]) < 0.02 && Math.abs(k[1] - want[i][1]) < 0.01)

const j = (v) => JSON.stringify(JSON.stringify(v))
const NAME = `${j(base.compName)}.replace(/"/g, '')`
const runner = `// generated by test/run-rebuild.mjs -- ES3
try { app.preferences.savePrefAsLong('Main Pref Section', 'Pref_SCRIPTING_FILE_NETWORK_SECURITY', 1); } catch (e) {}
$.evalFile(${JSON.stringify(join(root, 'cep/host/index.jsx'))});
function WRITE(name, s) { var f = new File(${JSON.stringify(dir)} + '/' + name); f.encoding = 'UTF-8'; f.open('w'); f.write(s); f.close(); }
function BUILD(jsonPath) {
  WALLMAKER.begin(WALLMAKER_JSON.stringify({ jsonPath: jsonPath, folder: ${JSON.stringify(dir)} }));
  var guard = 0;
  while (guard++ < 200) { var s = WALLMAKER_JSON.parse(WALLMAKER.step('{"count":25}')); if (s.done >= s.total) break; }
  return WALLMAKER_JSON.parse(WALLMAKER.finish());
}
function findComp(name) { var it = app.project.items; for (var i = 1; i <= it.length; i++) if (it[i] instanceof CompItem && it[i].name === name) return it[i]; return null; }
function byName(comp, nm) { for (var i = 1; i <= comp.numLayers; i++) if (comp.layer(i).name === nm) return comp.layer(i); return null; }
function zoomProp(comp) { var c = byName(comp, 'Wallmaker Camera'); return c ? c.property('ADBE Effect Parade').property('Zoom to screen (%)').property(1) : null; }
function keysOf(p) { var a = []; for (var i = 1; i <= p.numKeys; i++) a.push([Math.round(p.keyTime(i) * 1000) / 1000, Math.round(p.keyValue(i) * 100) / 100]); return a; }
function slider(comp, nm) { var c = byName(comp, 'Wallmaker Controls'); return c.property('ADBE Effect Parade').property(nm).property(1); }
try {
  try { app.project.close(CloseOptions.DO_NOT_SAVE_CHANGES); } catch (e) {}
  app.newProject();
  var out = {};
  out.fin1 = BUILD(${JSON.stringify(join(dir, 'wall1.json'))});
  var comp = findComp(${NAME});
  var compId = comp.id;
  out.keys1 = keysOf(zoomProp(comp));
  out.ctlParent = byName(comp, 'Wallmaker Controls').parent ? byName(comp, 'Wallmaker Controls').parent.name : null;
  out.ctlPos = byName(comp, 'Wallmaker Controls').property('ADBE Transform Group').property('ADBE Position').value;

  // -- the user customizes: Gap slider to 33 and a layer of their own (camera keys untouched)
  slider(comp, 'Gap (px)').setValue(33);
  var userLayer = comp.layers.addSolid([1, 0, 0], 'user layer', 50, 50, 1, comp.duration);
  userLayer.comment = 'mine';

  // -- rebuild #1: untouched camera keys must FOLLOW the panel's new move
  out.fin2 = BUILD(${JSON.stringify(join(dir, 'wall2.json'))});
  var c2 = findComp(${NAME});
  out.sameCompId = c2.id === compId;
  out.keys2 = keysOf(zoomProp(c2));
  out.gapVal = slider(c2, 'Gap (px)').value;
  out.revealVal = slider(c2, 'Reveal start (s)').value;
  out.screens = 0; out.userSeen = false; out.stale = 0; out.cameras = 0;
  for (var m = 1; m <= c2.numLayers; m++) {
    var l = c2.layer(m);
    var cm = String(l.comment || '');
    if (cm.indexOf('wallmaker-screen') === 0) out.screens++;
    if (cm.indexOf('wallmaker-camera') === 0) out.cameras++;
    if (cm.indexOf('wallmaker-label') === 0 || cm.indexOf('wallmaker-borders') === 0 || cm.indexOf('wallmaker-focus') === 0) out.stale++;
    if (l.name === 'user layer') out.userSeen = true;
  }
  out.comps = 0;
  var items = app.project.items;
  for (var k = 1; k <= items.length; k++) if (items[k] instanceof CompItem && items[k].name === ${NAME}) out.comps++;
  out.probe = WALLMAKER_JSON.parse(WALLMAKER.probe(WALLMAKER_JSON.stringify({ compName: ${NAME}, time: 6 })));

  // -- the user retimes the camera by hand: drag the last zoom key out to 5 s
  var zp = zoomProp(c2);
  var lastV = zp.keyValue(zp.numKeys);
  zp.removeKey(zp.numKeys);
  zp.setValueAtTime(5, lastV);
  out.keysEdited = keysOf(zp);

  // -- rebuild #2: the hand-edited keys are the user's and must survive verbatim
  out.fin3 = BUILD(${JSON.stringify(join(dir, 'wall3.json'))});
  var c3 = findComp(${NAME});
  out.keys3 = keysOf(zoomProp(c3));
  out.revealVal3 = slider(c3, 'Reveal start (s)').value;
  out.keptCamKeys = out.fin3.keptCamKeys;

  // -- remove the build entirely
  out.removed = WALLMAKER_JSON.parse(WALLMAKER.remove(WALLMAKER_JSON.stringify({ buildKey: ${j(walls.wall2.buildKey)}.replace(/"/g, '') }))).removed;
  out.compsAfter = 0;
  var items2 = app.project.items;
  for (var q = 1; q <= items2.length; q++) if (items2[q] instanceof CompItem && items2[q].name === ${NAME}) out.compsAfter++;
  out.ok = true;
  WRITE('result.json', WALLMAKER_JSON.stringify(out));
} catch (e) {
  WRITE('result.json', WALLMAKER_JSON.stringify({ ok: false, error: String(e && e.message ? e.message + ' (line ' + e.line + ')' : e) }));
}
`
writeFileSync(join(dir, 'runner.jsx'), runner)
console.log('=== Round E: build → customize → rebuild ×2 → remove…')
execSync(`osascript -e 'with timeout of 900 seconds' -e 'tell application "${AE}" to DoScript "$.evalFile(\\"${join(dir, 'runner.jsx')}\\")"' -e 'end timeout'`, { stdio: 'inherit' })
const r = JSON.parse(readFileSync(join(dir, 'result.json'), 'utf8'))
if (!r.ok) throw new Error(`Round E failed in AE: ${r.error}`)

// the rebuilt screens must sit on wall2's 5x5 grid -- with the user's Gap=33 (their slider survives,
// so the live position expressions use 33 while cell sizes come from wall2's plan)
const g2 = walls.wall2.grid
const posOk = (r.probe ?? []).every((row) => {
  const spec = walls.wall2.screens.find((s) => s.i === row.idx)
  const ex = (spec.col - (g2.cols - 1) / 2) * (g2.cellW + 33)
  const ey = (spec.row - (g2.rows - 1) / 2) * (g2.cellH + 33)
  return Math.abs(row.pos[0] - ex) < 0.6 && Math.abs(row.pos[1] - ey) < 0.6
})

const n1 = walls.wall1.screens.length
const n2 = walls.wall2.screens.length
const checks = [
  [`first build: ${n1} screens`, r.fin1.screens === n1],
  ['camera wrote the planned zoom keyframes', sameKeys(r.keys1, planKeys(walls.wall1)), `${JSON.stringify(r.keys1)} vs ${JSON.stringify(planKeys(walls.wall1))}`],
  ['the wall null hangs off the camera null at its origin', r.ctlParent === 'Wallmaker Camera' && Math.abs(r.ctlPos[0]) < 0.01 && Math.abs(r.ctlPos[1]) < 0.01],
  [`second build: ${n2} screens`, r.fin2.screens === n2 && r.screens === n2],
  ["rebuilt screens sit on wall2's grid (with the user's kept Gap=33)", posOk && (r.probe ?? []).length === n2],
  ['comp item identity preserved', r.sameCompId === true],
  ['exactly one comp with that name, one camera null', r.comps === 1 && r.cameras === 1],
  ['no stale label / border / focus layers from older builds', r.stale === 0],
  ["user's own layer survived", r.userSeen === true],
  ["user's slider value survived (33)", Math.abs(r.gapVal - 33) < 0.01],
  ['untouched slider followed the panel (Reveal start 0.3 → 1.7)', Math.abs(r.revealVal - 1.7) < 0.01],
  ['untouched camera keys followed the panel', sameKeys(r.keys2, planKeys(walls.wall2)), `${JSON.stringify(r.keys2)} vs ${JSON.stringify(planKeys(walls.wall2))}`],
  ['hand-retimed camera keys survived the rebuild verbatim', sameKeys(r.keys3, r.keysEdited), `${JSON.stringify(r.keys3)} vs ${JSON.stringify(r.keysEdited)}`],
  ['the build reported that it kept your camera keys', r.keptCamKeys === true],
  ['sliders still followed the panel on that same rebuild (Reveal start → 2.4)', Math.abs(r.revealVal3 - 2.4) < 0.01],
  ['remove() removed the build', r.removed === true && r.compsAfter === 0],
]
let bad = 0
for (const [name, ok, detail] of checks) {
  console.log(` ${ok ? '✓' : '✗'} ${name}${!ok && detail ? ` — ${detail}` : ''}`)
  if (!ok) bad++
}
if (bad) {
  console.log(JSON.stringify(r, null, 2))
  process.exit(1)
}
console.log('✓ Round E passed')
